name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OctoHR

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.6
    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.ConfigDbMigrator"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.DatabaseMigrator"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.PublicWebApp"
    - name: Publish ConfigDbMigrator
      run: dotnet publish OctopusSamples.OctoHR.ConfigDbMigrator/OctopusSamples.OctoHR.ConfigDBMigrator.csproj -r win-x64 --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.ConfigDbMigrator"
    - name: Publish DatabaseMigrator
      run: dotnet publish OctopusSamples.OctoHR.DatabaseMigrator/OctopusSamples.OctoHR.DatabaseMigrator.csproj -r win-x64 --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.DatabaseMigrator"
    - name: Publish PublicWebApp
      run: dotnet publish OctopusSamples.OctoHR.PublicWebApp/OctopusSamples.OctoHR.PublicWebApp.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.PublicWebApp"
    - name: Package ConfigDbMigrator
      run: |
        octo pack --id="OctoHR.ConfigDbMigrator" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.ConfigDbMigrator" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Package DatabaseMigrator
      run: |
        octo pack --id="OctoHR.DatabaseMigrator" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.DatabaseMigrator" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Package PublicWebApp
      run: |
        octo pack --id="OctoHR.PublicWebApp" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoHR.PublicWebApp" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Push ConfigDbMigrator
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoHR.ConfigDbMigrator.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"
    - name: Push DatabaseMigrator
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoHR.DatabaseMigrator.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"
    - name: Push OctoHR.PublicWebApp
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoHR.PublicWebApp.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"
